# Setup
title:            Vinayak Nayak
tagline:          ''
description:      ''
url:              https://elisonsherton.github.io/
baseurl:          https://elisonsherton.github.io/

author:
  name:           'Vinayak Nayak'
  url:            https://twitter.com/ElisonSherton

paginate:         5
kramdown:
  math_engine: katex
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ElisonSherton/elisonsherton.github.io/
