# Setup
title:            Vinayak Nayak
tagline:          ''
description:      'Mechanical Engineer, AI Developer. <a href="https://twitter.com/ElisonSherton" target="_blank">@ElisonSherton</a>.'
url:              https://elisonsherton.github.io/
baseurl:          https://elisonsherton.github.io/

author:
  name:           'Vinayak Nayak'
  url:            https://twitter.com/ElisonSherton

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ElisonSherton/elisonsherton.github.io/
